### ISSUE TITLE
PLANTS is running in the background after cancellation

### ISSUE THREAD

**Issue by AJK-dev** [3D-e-Chem/knime-plants#12]
When an executing "PLANTS runner" node is cancelled only the node execution is interrupted. The PLANTS executable itself will still continue to run in the background.

Test environment: 3D-e-Chem-VM using VirtualBox

**Comment by sverhoeven** [comment]
The KNIME `ExecutionContext.checkCanceled()` is checked after each row and the process uses `waitFor()` to block the node execute thread.

The the `waitFor()` should be called in a sleep while loop with a call to `checkCanceled()` so the process can be destroyed gracefully.
