### ISSUE TITLE
Pocket node to define the pocket for PLANTS docking

### ISSUE THREAD

**Issue by sverhoeven** [3D-e-Chem/knime-plants#2]
Pocket can be defined in multiple ways:

* Select ligand inside protein
* Select residues by number
* Select residues by mol2

**Comment by AJK-dev** [comment]
Bindingsite definition for PLANTS docking (from manual):
This mode calculates a sphere containing the ligand molecule.mol2. The user can specify an additional distance x that is added to the sphere radius:
<code>PLANTS --mode bind molecule.mol2 x [protein.mol2]</code>

Output:
• bindingsite.def: Spherical bindingsite definition.
• PLANTSactiveSite.mol2: Active site atoms as used inside PLANTS, i.e. all atoms that lie inside the sphere (only written if protein file specified).
• PLANTSactiveSiteResidues.mol2: Complete active site residues (only written if protein file specified).

-- 

Example syntax for defining docking pocket using PLANTS.

Option 1: Reference Ligand (ligand.mol2) with an additional radius of 6Å:
<code>PLANTS --mode bind ligand.mol2 6</code>

Option 2: Reference pocket (pocket.mol2):
<code>PLANTS --mode bind pocket.mol2 0</code>

Then read the _bindingsite_center_ and _bindingsite_radius_ variables from _plants_pocket.log_ and include them in the PLANTS configuration.

Option 3: When defining the pocket based on residues numbers this can be done directly within the PLANTS configuration using the _use_gold_bindingsite_ setting. Create a text file listing the pocket residues using the 3-letter abbreviations + numbering, one on each line. Then include the following in the PLANTS configuration:
<code>use_gold_bindingsite gold_pocket.txt</code>

Example contents gold_pocket.txt:
> VAL76
> VAL80
> ASN84
> TRP103
> LEU104
> ASP107
> TYR108
> VAL109
> ALA110
> SER111
> THR112
> ALA113
> SER114
> ILE115
> PHE116
> TRP158
> LYS179
> THR182
> PHE184
> PHE190
> LYS191
> VAL192
> MET193
> THR194
> ALA195
> ILE196
> ASN198
> PHE199
> PRO202
> PHE424
> TRP428
> TYR431
> PHE432
> PHE435
> HIS450
> THR453
> ILE454
> TRP455
> GLY457
> TYR458

**Comment by sverhoeven** [comment]
Implemented `plants --mode bind <ligand-or-pocket.mol2>` as a metanode called `PLANTS bindingsite`.
